// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY'),
    appId: '1:787114932879:web:557e51076d266b1f4a4efa',
    messagingSenderId: '787114932879',
    projectId: 'my-flutter-app-7bb47',
    authDomain: 'my-flutter-app-7bb47.firebaseapp.com',
    storageBucket: 'my-flutter-app-7bb47.firebasestorage.app',
    measurementId: 'G-9MR0H89QZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY'),
    appId: '1:787114932879:android:329ba245fec062914a4efa',
    messagingSenderId: '787114932879',
    projectId: 'my-flutter-app-7bb47',
    storageBucket: 'my-flutter-app-7bb47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY'),
    appId: '1:787114932879:ios:5f97f2bcfd0aa7ba4a4efa',
    messagingSenderId: '787114932879',
    projectId: 'my-flutter-app-7bb47',
    storageBucket: 'my-flutter-app-7bb47.firebasestorage.app',
    iosBundleId: 'page.hopital.hospitalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY'),
    appId: '1:787114932879:ios:5f97f2bcfd0aa7ba4a4efa',
    messagingSenderId: '787114932879',
    projectId: 'my-flutter-app-7bb47',
    storageBucket: 'my-flutter-app-7bb47.firebasestorage.app',
    iosBundleId: 'page.hopital.hospitalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY'),
    appId: '1:787114932879:web:69919831d8464f694a4efa',
    messagingSenderId: '787114932879',
    projectId: 'my-flutter-app-7bb47',
    authDomain: 'my-flutter-app-7bb47.firebaseapp.com',
    storageBucket: 'my-flutter-app-7bb47.firebasestorage.app',
    measurementId: 'G-G4KFJ90V14',
  );

}
